#! bin/env bash
set -eux
sudo wget -O /etc/yum.repos.d/jenksin.repo \
	http://pkg.jenkins-ci.org/redhat/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
sudo yum install java-1.8.0 -y
sudo yum install jenkins -y
sudo systemctl start jenkins.service
sudo systemctl enable jenkins.service